name: Re-use other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: eddyniemeijer/my-first-workflow/.github/workflows/reusable.yml
    with:
      who-to-greet: '@eddyniemeijer'
  
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      -run: echo "Time ${{ needs.call-workflow.outputs.current-time }}"
